#page title
page_title                                : Not Evil Sudoku                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://www.ashishselvaraj.com/                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Not Evil Sudoku                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : No ads. No sign up. Simply Sudoku.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ashish Selvaraj                               
your_link                                 : https://www.ashishselvaraj.com/                   
your_city                                 :                                
email_address                             : not.evil.sudoku@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : selvarajashish
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : No Ads
    description                           : Most sudoku apps are filled with ads. Not Evil Sudoku is not one of them.
    fontawesome_icon_name                 : magic
    
  - title                                 : Timer
    description                           : See how fast you can solve a puzzle and keep track of your improvement.
    fontawesome_icon_name                 : stopwatch

  - title                                 : Difficulty Modes
    description                           : Pick a difficulty mode that suits you.
    fontawesome_icon_name                 : chess-knight

  - title                                 : Undo
    description                           : Undo any moves you may regret.
    fontawesome_icon_name                 : undo

  - title                                 : Notes
    description                           : Keep track of which numbers you think may belong in a square.
    fontawesome_icon_name                 : clipboard

  - title                                 : Streak
    description                           : Develop a daily sudoku habit and keep track of your streak.
    fontawesome_icon_name                 : fire
  
  - title                                 : Best Time
    description                           : See your best time to solve a sudoku game in each difficulty mode.
    fontawesome_icon_name                 : medal

  - title                                 : Charts
    description                           : See your progress over time and over difficulty.
    fontawesome_icon_name                 : chart-line

  - title                                 : App Icons
    description                           : Fun alternate app icons to liven up your home screen.
    fontawesome_icon_name                 : umbrella-beach

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 1.0

device_color                              : coral                                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "##db4918"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "##db4918"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
