#page title
app_title                                : Not Evil Sudoku                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1614071642                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apple.co/3vyesUR                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://www.notevil.app/not-evil-sudoku-press-kit.zip                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Not Evil Sudoku                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : No ads, no tracking, no data mining. Just a clean, minimalist sudoku app built natively for iPhone and iPad.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ashish Selvaraj                               
your_link                                 : https://www.ashishselvaraj.com/                   
your_city                                 :                                
email_address                             : sudoku@notevil.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : selvarajashish
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : No Ads
    description                           : Most sudoku apps are filled with ads. Not Evil Sudoku is not one of them.
    fontawesome_icon_name                 : magic
    
  - title                                 : Daily Puzzles
    description                           : A puzzle for every day synced across all users.
    fontawesome_icon_name                 : calendar

  - title                                 : Leaderboards
    description                           : See where your solve times rank across your friends and all players.
    fontawesome_icon_name                 : star

  - title                                 : Game Settings
    description                           : Powerful customization to tailor your experience.
    fontawesome_icon_name                 : wrench

  - title                                 : Notes
    description                           : Keep track of which numbers you think may belong in a square.
    fontawesome_icon_name                 : clipboard

  - title                                 : Streak
    description                           : Develop a daily sudoku habit and keep track of your streak.
    fontawesome_icon_name                 : fire
  
  - title                                 : Best Time
    description                           : See your best times across difficulty modes.
    fontawesome_icon_name                 : medal

  - title                                 : Charts
    description                           : See your progress over time and across difficulties.
    fontawesome_icon_name                 : chart-line

  - title                                 : App Icons
    description                           : Fun alternate app icons to liven up your home screen.
    fontawesome_icon_name                 : umbrella-beach

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#f8f2eb"
topbar_transparency                       : 1.0
topbar_title_color                        : "#002a44"

cover_image                               : 'assets/headerimage.png'
cover_overlay_color                       : "#fffaf4"
cover_overlay_transparency                : 0.5

device_color                              : frame

body_background_color                     : "#fffaf4"

link_color                                : "#297ec0"

app_title_color                           : "#002a44"
app_price_color                           : "#333333"
app_description_color                     : "#333333"

feature_title_color                       : "#002a44"
feature_text_color                        : "#333333"

feature_icons_foreground_color            : "#002a44"
feature_icons_background_color            : "#f8f2eb"

social_icons_foreground_color             : "#002a44"
social_icons_background_color             : "#f8f2eb"

footer_text_color                         : "#333333"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

url: "https://notevil.io" 
baseurl: ""  
plugins:
  - jekyll-sitemap